# $Id: Makefile,v 1.2 2004/07/03 00:38:20 cmatsuoka Exp $

TOPDIR	= ..

XCFLAGS	=
OBJS	=
DFILES	= Makefile AUTHORS Artistic Copyright.ymf262 README.docs \
	  README.player mmf_format.txt Mtsu.txt vm3fmt.txt Pat.txt \
	  fmchips.html fmchips2.txt opl3.txt ma3.txt sbi.txt ibk.txt
CFILES	=
DCFILES	=
DDIRS	=

all:

include $(TOPDIR)/Make.rules

