# $Id: Makefile,v 1.1 2004/06/30 17:28:48 cmatsuoka Exp $

TOPDIR	= ../..

XCFLAGS	= -I..
XDEPS	=
OBJS	= mixer.o
DFILES	= Makefile $(OBJS:.o=.c) $(XDEPS)
CFILES	= $(LIB)
DCFILES	=
DDIRS	=
LIBS	=
LIB	= libbuzzer.a
BIN	=


all: $(LIB)

include $(TOPDIR)/Make.rules

